# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('vacation', 'Vacation Leave'), ('commuted', 'Commuted Leave'), ('special_casual', 'Special Casual Leave'), ('restricted', 'Restricted Leave'), ('station', 'Station Leave')], max_length=20)),
                ('applied_time', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('leave_address', models.CharField(blank=True, max_length=100)),
                ('processing_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('processing', 'Being Processed')], default='processing', max_length=20)),
                ('replacing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RemainingLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.IntegerField(default=30)),
                ('vacation', models.IntegerField(default=60)),
                ('commuted', models.IntegerField(default=10)),
                ('special_casual', models.IntegerField(default=15)),
                ('restricted', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remaining_leave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicationrequest',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_request', to='leavemodule.Leave'),
        ),
        migrations.AddField(
            model_name='applicationrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
