# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='id',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
