# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0002_auto_20170830_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_id',
        ),
        migrations.AddField(
            model_name='leave',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
