# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0004_auto_20170830_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_id',
        ),
        migrations.AddField(
            model_name='leave',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
