# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemodule', '0007_auto_20170830_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_id',
            field=models.IntegerField(null=True),
        ),
    ]
