# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyDepartment', models.CharField(choices=[('ME', 'Mechanical Engineering'), ('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and communication Engineering'), ('NS', 'Natural Science'), ('Design', 'Design')], max_length=100)),
                ('facultyLeaveHead', models.CharField(choices=[('head', 'head'), ('director', 'director')], max_length=100)),
                ('facultyDesignation', models.CharField(blank=True, choices=[('deanRSPC', 'dean RSPC'), ('hodme', 'hod ME'), ('hodcse', 'hod CSE'), ('headns', 'head NS'), ('deanacad', 'dean academics'), ('deanstudents', 'dean students'), ('director', 'director')], max_length=100, null=True)),
                ('facultyPost', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Research Engineer', 'Research Engineer')], max_length=100, null=True)),
                ('pfnumber', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffDepartment', models.CharField(choices=[('fa', 'finance and accounts'), ('et', 'establishment'), ('academics', 'academics'), ('ece', 'ece'), ('academics', 'academics'), ('ns', 'natural science'), ('mechatronics', 'mechatronics'), ('pc', 'placement cell'), ('iwd', 'iwd'), ('otd', 'office of the dean'), ('directorate', 'directorate'), ('library', 'library')], max_length=100)),
                ('staffLeaveHead', models.CharField(choices=[('registrar', 'registrar'), ('deanacad', 'dean academics'), ('ccc', 'cordinator computer center'), ('hodece', 'hod ECE'), ('hodcse', 'hod CSE'), ('hodme', 'hod ME'), ('dean', 'dean'), ('iw', 'incharge workshop')], max_length=100)),
                ('staffDesignation', models.CharField(choices=[('sa', 'senior assistant'), ('ja', 'junior assistant'), ('st', 'senior techinician'), ('driver', 'driver'), ('jt', 'junior technician'), ('ar', 'assistant registrar'), ('ja', 'junior assistant'), ('dr', 'deputy registrar')], max_length=100)),
                ('staffPost', models.CharField(choices=[('sa', 'senior assistant'), ('ja', 'junior assistant'), ('st', 'senior techinician'), ('driver', 'driver'), ('jt', 'junior technician'), ('ar', 'assistant registrar'), ('ja', 'junior assistant'), ('dr', 'deputy registrar')], max_length=100)),
                ('pfnumber', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
