# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170829_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='facultyDepartment',
            field=models.CharField(choices=[('fa', 'finance and accounts'), ('et', 'establishment'), ('academics', 'academics'), ('ece', 'ece'), ('academics', 'academics'), ('ns', 'natural science'), ('mechatronics', 'mechatronics'), ('pc', 'placement cell'), ('iwd', 'iwd'), ('otd', 'office of the dean'), ('directorate', 'directorate'), ('library', 'library'), ('ME', 'Mechanical Engineering'), ('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and communication Engineering'), ('NS', 'Natural Science'), ('Design', 'Design')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='facultyLeaveHead',
            field=models.CharField(choices=[('registrar', 'registrar'), ('deanacad', 'dean academics'), ('ccc', 'cordinator computer center'), ('hodece', 'hod ECE'), ('hodcse', 'hod CSE'), ('hodme', 'hod ME'), ('dean', 'dean'), ('iw', 'incharge workshop'), ('head', 'head'), ('director', 'director')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='facultyPost',
            field=models.CharField(choices=[('sa', 'senior assistant'), ('ja', 'junior assistant'), ('st', 'senior techinician'), ('driver', 'driver'), ('jt', 'junior technician'), ('ar', 'assistant registrar'), ('ja', 'junior assistant'), ('dr', 'deputy registrar'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Research Engineer', 'Research Engineer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='facultyPostForLeave',
            field=models.CharField(blank=True, choices=[('registrar', 'registrar'), ('deanacad', 'dean academics'), ('ccc', 'cordinator computer center'), ('hodece', 'hod ECE'), ('hodcse', 'hod CSE'), ('hodme', 'hod ME'), ('dean', 'dean'), ('iw', 'incharge workshop'), ('head', 'head'), ('director', 'director')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
